const AUTHENTICATION = {
  CREATE_SUCCESS: 'create user success',
  UPDATE_SUCCESS: 'update user success',
  DELETE_SUCCESS: 'delete user success',

  CREATE_ERROR: 'create user error',
  UPDATE_ERROR: 'update user error',
  DELETE_ERROR: 'delete user error',
};

const LOGIN = {
  LOGIN_SUCCESS: 'login success',
  WRONG_USER_EMAIL_OR_PASSWORD: 'wrong user email or password',
  USER_NOT_EXIST: 'user not exist',
};

const FORGET_RESET_PASSWORD = {
  SEND_EMAIL_SUCCESS: 'SEND_EMAIL_SUCCESS',
  SEND_EMAIL_FAIL: 'SEND_EMAIL_FAIL',

  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',

  WRONG_OTP: 'WRONG_OTP',
  WRONG_EMAIL: 'WRONG_EMAIL',
  WRONG_CURRENT_PASSWORD: 'WRONG_CURRENT_PASSWORD',
  NOT_FOUND_EMAIL: 'NOT_FOUND_EMAIL',
  TOKEN_IS_INVALID: 'TOKEN_IS_INVALID',
  DUPLICATE_NEW_CURRENT_PASSWORD: 'DUPLICATE_NEW_CURRENT_PASSWORD',
};

export const USER = {
  NOT_FOUND_USER: 'NOT_FOUND_USER',

  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
};

export const HTTP_RESPONSE_MESSAGE = {
  AUTHENTICATION: { ...AUTHENTICATION },
  LOGIN: { ...LOGIN },
  FORGET_RESET_PASSWORD: { ...FORGET_RESET_PASSWORD },
  USER: { ...USER },

  SERVER_ERROR: 'SERVER_ERROR',
};
